import dotenv from 'dotenv';
dotenv.config();

import { supabase } from '../src/lib/supabase';

interface Exercise {
  slug: string;
  name: string;
  muscle_groups: string[];
  equipment: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  instructions: string[];
  image_url: null;
  video_url: null;
}

function ex(
  slug: string,
  name: string,
  muscle_groups: string[],
  equipment: string[],
  difficulty: 'beginner' | 'intermediate' | 'advanced',
  instructions: string[]
): Exercise {
  return { slug, name, muscle_groups, equipment, difficulty, instructions, image_url: null, video_url: null };
}

const EXERCISES: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────────────
  ex('barbell-bench-press', 'Barbell Bench Press', ['chest','triceps','shoulders'], ['barbell'], 'intermediate',
    ['Lie on bench, eyes under bar, feet flat on floor', 'Grip bar slightly wider than shoulder width', 'Lower bar to lower chest, elbows at ~75 degrees', 'Press back up explosively to full lockout']),
  ex('incline-barbell-bench-press', 'Incline Barbell Bench Press', ['chest','shoulders','triceps'], ['barbell'], 'intermediate',
    ['Set bench to 30-45 degrees, grip bar slightly wider than shoulders', 'Unrack and lower bar to upper chest under control', 'Press back up, squeezing the upper chest at the top']),
  ex('decline-barbell-bench-press', 'Decline Barbell Bench Press', ['chest','triceps'], ['barbell'], 'intermediate',
    ['Set bench to -15 to -30 degrees, feet secured', 'Grip bar wider than shoulder width', 'Lower bar to lower chest, press back to lockout']),
  ex('incline-dumbbell-press', 'Incline Dumbbell Press', ['chest','shoulders','triceps'], ['dumbbells'], 'intermediate',
    ['Set bench to 30-45 degree incline, dumbbells at shoulder height', 'Press dumbbells up and slightly together', 'Lower under control to upper chest level', 'Keep shoulder blades retracted throughout']),
  ex('decline-dumbbell-press', 'Decline Dumbbell Press', ['chest','triceps'], ['dumbbells'], 'intermediate',
    ['Set bench to decline, hold dumbbells at chest level', 'Press up explosively, do not lock out elbows fully', 'Lower slowly back to start']),
  ex('dumbbell-fly', 'Dumbbell Fly', ['chest'], ['dumbbells'], 'beginner',
    ['Lie flat on bench, dumbbells above chest, slight bend in elbows', 'Lower dumbbells out to sides in an arc until you feel a chest stretch', 'Squeeze chest to bring dumbbells back together above sternum']),
  ex('incline-dumbbell-fly', 'Incline Dumbbell Fly', ['chest'], ['dumbbells'], 'beginner',
    ['Set bench to 30 degrees incline', 'Hold dumbbells above chest with slight elbow bend', 'Open arms in a wide arc, feel the upper chest stretch', 'Contract chest to close the arc']),
  ex('cable-chest-fly', 'Cable Chest Fly', ['chest'], ['cables'], 'beginner',
    ['Set cables to shoulder height, stand in the middle', 'Hold handles with slight elbow bend, lean slightly forward', 'Bring hands together in front of chest in a hugging motion', 'Return slowly to starting position']),
  ex('cable-crossover', 'Cable Crossover', ['chest'], ['cables'], 'intermediate',
    ['Set cables high, stand in center', 'Pull handles down and together in front of your waist', 'Cross hands slightly at the bottom for peak contraction', 'Return slowly with arms extended']),
  ex('chest-dip', 'Chest Dip', ['chest','triceps','shoulders'], ['bodyweight'], 'intermediate',
    ['Grip parallel bars and lock arms out', 'Lean torso forward 30 degrees to emphasize chest', 'Descend until upper arms are parallel to floor', 'Press back up to lockout']),
  ex('push-up', 'Push-Up', ['chest','triceps','shoulders'], ['bodyweight'], 'beginner',
    ['Place hands slightly wider than shoulders, body straight from head to heels', 'Lower chest toward floor, elbows at 45-degree angle', 'Push back up to full arm extension']),
  ex('wide-grip-push-up', 'Wide-Grip Push-Up', ['chest'], ['bodyweight'], 'beginner',
    ['Place hands much wider than shoulders', 'Lower chest to floor with elbows flaring out', 'Drive back up, squeezing chest at top']),
  ex('diamond-push-up', 'Diamond Push-Up', ['triceps','chest'], ['bodyweight'], 'intermediate',
    ['Place hands together under chest forming a diamond shape', 'Lower chest toward hands, elbows tracking back', 'Press back up to full extension']),
  ex('machine-chest-press', 'Machine Chest Press', ['chest','triceps','shoulders'], ['machines'], 'beginner',
    ['Adjust seat so handles are at mid-chest level', 'Press handles forward until arms are nearly extended', 'Return slowly, feeling a chest stretch at the bottom']),
  ex('pec-deck', 'Pec Deck Machine', ['chest'], ['machines'], 'beginner',
    ['Sit with back flat against pad, forearms on the pads', 'Bring arms together in front of you, squeezing chest at peak', 'Return slowly to full stretch']),

  // ── BACK ───────────────────────────────────────────────────────────
  ex('conventional-deadlift', 'Conventional Deadlift', ['hamstrings','glutes','back','traps'], ['barbell'], 'intermediate',
    ['Stand with feet hip-width apart, bar over mid-foot', 'Hinge at hips, grip bar just outside legs', 'Flatten back, chest up, shoulders over bar', 'Drive feet into floor and extend hips and knees simultaneously', 'Lock out at top, then hinge back down under control']),
  ex('romanian-deadlift', 'Romanian Deadlift', ['hamstrings','glutes','back'], ['barbell'], 'intermediate',
    ['Hold barbell at hip height, feet hip-width apart', 'Hinge at hips pushing them back, bar stays close to legs', 'Lower until strong hamstring stretch', 'Drive hips forward, squeeze glutes at top']),
  ex('sumo-deadlift', 'Sumo Deadlift', ['glutes','hamstrings','back'], ['barbell'], 'intermediate',
    ['Stand wide with toes turned out, grip bar inside legs', 'Drop hips lower than conventional, chest tall', 'Drive knees out and hips forward to lockout']),
  ex('barbell-bent-over-row', 'Barbell Bent-Over Row', ['back','biceps','core'], ['barbell'], 'advanced',
    ['Hinge at hips, torso near parallel to floor', 'Grip bar overhand, hands shoulder-width', 'Row bar to lower chest, elbows drive back', 'Squeeze lats at top, lower under control', 'Keep spine neutral throughout']),
  ex('cable-lat-pulldown', 'Cable Lat Pulldown', ['back','biceps'], ['cables'], 'beginner',
    ['Sit with thighs secured, grip bar wide overhand', 'Lean back slightly, pull bar to upper chest', 'Squeeze lats, return bar overhead under control']),
  ex('pull-up', 'Pull-Up', ['back','biceps','core'], ['bodyweight','pull_up_bar'], 'intermediate',
    ['Hang overhand, hands shoulder-width', 'Depress shoulder blades, engage lats', 'Pull chin over bar driving elbows down and back', 'Lower fully under control']),
  ex('chin-up', 'Chin-Up', ['back','biceps'], ['bodyweight','pull_up_bar'], 'intermediate',
    ['Hang underhand, hands shoulder-width', 'Pull chest to bar, elbows drive toward hips', 'Squeeze biceps and back at top', 'Lower fully']),
  ex('neutral-grip-pull-up', 'Neutral-Grip Pull-Up', ['back','biceps'], ['bodyweight','pull_up_bar'], 'intermediate',
    ['Use parallel grip handles or parallel bar', 'Hang with palms facing each other', 'Pull chest to bar, leading with elbows', 'Lower under control']),
  ex('single-arm-dumbbell-row', 'Single-Arm Dumbbell Row', ['back','biceps'], ['dumbbells'], 'beginner',
    ['Place hand and knee on bench for support', 'Hold dumbbell with free hand, arm extended', 'Row dumbbell to hip, driving elbow straight back', 'Squeeze lat at top, lower slowly']),
  ex('cable-seated-row', 'Cable Seated Row', ['back','biceps'], ['cables'], 'beginner',
    ['Sit at cable row station with feet on platform', 'Grip handle and pull to lower abdomen, chest up', 'Squeeze shoulder blades together', 'Return arms to full extension']),
  ex('t-bar-row', 'T-Bar Row', ['back','biceps'], ['barbell'], 'intermediate',
    ['Straddle a landmine barbell or T-bar machine', 'Grip handles, hinge forward at 45-75 degrees', 'Row bar to chest, elbows drive back', 'Lower fully under control']),
  ex('pendlay-row', 'Pendlay Row', ['back','biceps'], ['barbell'], 'advanced',
    ['Bar starts on floor each rep, torso parallel to floor', 'Explosively row bar to lower chest', 'Lower bar completely to floor, reset, repeat']),
  ex('reverse-grip-lat-pulldown', 'Reverse-Grip Lat Pulldown', ['back','biceps'], ['cables'], 'beginner',
    ['Grip bar underhand, shoulder-width', 'Pull bar to upper chest, elbows track down and in', 'Squeeze lats, return under control']),
  ex('straight-arm-pulldown', 'Straight-Arm Pulldown', ['back'], ['cables'], 'beginner',
    ['Stand facing high cable, hold bar with straight arms', 'Push bar down in a sweeping arc to thighs', 'Feel lat stretch at top, squeeze at bottom']),
  ex('cable-face-pull', 'Cable Face Pull', ['shoulders','back'], ['cables'], 'beginner',
    ['Set cable to head height with rope attachment', 'Pull rope to face, elbows high and wide', 'Separate hands as you pull, squeeze rear delts', 'Return slowly']),
  ex('resistance-band-face-pull', 'Resistance Band Face Pull', ['shoulders','back'], ['resistance_bands'], 'beginner',
    ['Anchor band at face height', 'Step back for tension, pull band toward face', 'Elbows high and flared, squeeze rear delts', 'Return slowly']),
  ex('machine-row', 'Machine Row', ['back','biceps'], ['machines'], 'beginner',
    ['Adjust chest pad, grip handles at shoulder width', 'Row handles to chest, squeezing shoulder blades', 'Return to full extension']),
  ex('hyperextension', 'Back Extension (Hyperextension)', ['back','glutes','hamstrings'], ['machines'], 'beginner',
    ['Secure feet on hyperextension bench, arms crossed or behind head', 'Lower torso down toward floor', 'Raise back to parallel or slightly above using spinal erectors', 'Do not hyperextend']),
  ex('good-morning', 'Good Morning', ['back','hamstrings','glutes'], ['barbell'], 'advanced',
    ['Bar on upper back, feet shoulder-width', 'Hinge at hips, keep back flat, lower torso forward', 'Feel hamstring stretch, drive hips forward to return']),
  ex('rack-pull', 'Rack Pull', ['back','traps','glutes'], ['barbell'], 'intermediate',
    ['Set bar at knee height on rack pins', 'Grip and deadlift from this elevated position', 'Focus on upper back and traps, lockout hard at top']),
  ex('inverted-row', 'Inverted Row', ['back','biceps','core'], ['bodyweight'], 'beginner',
    ['Set bar at waist height, hang below with arms extended', 'Body straight, pull chest to bar', 'Squeeze shoulder blades at top, lower under control']),

  // ── SHOULDERS ──────────────────────────────────────────────────────
  ex('barbell-overhead-press', 'Barbell Overhead Press', ['shoulders','triceps','core'], ['barbell'], 'intermediate',
    ['Bar at collarbone, elbows slightly in front', 'Brace core and glutes', 'Press straight up, move head back then forward', 'Lock out overhead, shrug traps slightly', 'Lower to clavicle under control']),
  ex('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', ['shoulders','triceps'], ['dumbbells'], 'beginner',
    ['Sit with back support, dumbbells at shoulder height', 'Press straight up, arms fully extended', 'Do not shrug excessively', 'Lower to shoulder height under control']),
  ex('arnold-press', 'Arnold Press', ['shoulders','triceps'], ['dumbbells'], 'intermediate',
    ['Start with dumbbells in front of face, palms facing you', 'As you press up, rotate palms forward', 'Reach full extension at top with palms facing away', 'Reverse rotation on the way down']),
  ex('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', ['shoulders'], ['dumbbells'], 'beginner',
    ['Stand with dumbbells at sides, slight elbow bend', 'Raise arms out to sides to shoulder height', 'Lead with elbows not wrists, pause at top', 'Lower slowly']),
  ex('dumbbell-front-raise', 'Dumbbell Front Raise', ['shoulders'], ['dumbbells'], 'beginner',
    ['Stand with dumbbells in front of thighs', 'Raise one or both arms to shoulder height', 'Do not swing; lower slowly']),
  ex('cable-lateral-raise', 'Cable Lateral Raise', ['shoulders'], ['cables'], 'beginner',
    ['Stand beside low cable, hold handle in far hand', 'Raise arm out to shoulder height', 'Pause at top, return under control']),
  ex('dumbbell-reverse-fly', 'Dumbbell Reverse Fly', ['shoulders','back'], ['dumbbells'], 'beginner',
    ['Hinge forward at hips, dumbbells hanging', 'Raise arms out to sides, squeezing rear delts', 'Lower slowly']),
  ex('cable-reverse-fly', 'Cable Reverse Fly', ['shoulders','back'], ['cables'], 'beginner',
    ['Set cables at shoulder height, cross cables', 'Pull handles out to sides, squeezing rear delts', 'Return under control']),
  ex('barbell-upright-row', 'Barbell Upright Row', ['shoulders','traps'], ['barbell'], 'intermediate',
    ['Hold bar with narrow overhand grip at hip level', 'Pull bar straight up to chin, elbows lead and rise above bar', 'Lower slowly; keep bar close to body']),
  ex('barbell-shrug', 'Barbell Shrug', ['traps'], ['barbell'], 'beginner',
    ['Hold barbell in front, arms straight', 'Shrug shoulders straight up toward ears', 'Hold briefly at top, lower slowly']),
  ex('dumbbell-shrug', 'Dumbbell Shrug', ['traps'], ['dumbbells'], 'beginner',
    ['Hold dumbbells at sides', 'Shrug shoulders up, slight pause at top', 'Lower under control']),
  ex('machine-shoulder-press', 'Machine Shoulder Press', ['shoulders','triceps'], ['machines'], 'beginner',
    ['Adjust seat height so handles are at shoulder level', 'Press straight up to full extension', 'Return slowly to start']),
  ex('landmine-press', 'Landmine Press', ['shoulders','chest','triceps'], ['barbell'], 'intermediate',
    ['Hold end of landmine barbell at shoulder level', 'Press up and slightly forward', 'Control descent back to shoulder']),
  ex('push-press', 'Push Press', ['shoulders','triceps','legs'], ['barbell'], 'intermediate',
    ['Bar at collarbone, slight knee bend', 'Dip quickly and drive bar overhead with leg drive', 'Lockout overhead, lower under control']),
  ex('cable-shoulder-press', 'Seated Cable Shoulder Press', ['shoulders','triceps'], ['cables'], 'beginner',
    ['Sit with cables at shoulder level', 'Press handles overhead until arms extended', 'Lower slowly to start']),

  // ── BICEPS ─────────────────────────────────────────────────────────
  ex('dumbbell-bicep-curl', 'Dumbbell Bicep Curl', ['biceps'], ['dumbbells'], 'beginner',
    ['Stand with dumbbells at sides, palms forward', 'Curl both up toward shoulders, elbows fixed', 'Squeeze biceps at top', 'Lower slowly']),
  ex('barbell-curl', 'Barbell Curl', ['biceps'], ['barbell'], 'beginner',
    ['Stand holding barbell at hip level, underhand grip', 'Curl to shoulder height, elbows stay at sides', 'Lower under control']),
  ex('ez-bar-curl', 'EZ-Bar Curl', ['biceps'], ['barbell'], 'beginner',
    ['Grip EZ-bar at inner angled grips', 'Curl to shoulder height, elbows fixed', 'Lower slowly']),
  ex('incline-dumbbell-curl', 'Incline Dumbbell Curl', ['biceps'], ['dumbbells'], 'intermediate',
    ['Sit on 45-degree incline bench, arms hanging freely', 'Curl dumbbells with full range of motion', 'Longer stretch at bottom targets long head']),
  ex('hammer-curl', 'Hammer Curl', ['biceps','forearms'], ['dumbbells'], 'beginner',
    ['Hold dumbbells with neutral grip (palms facing each other)', 'Curl up without rotating wrist', 'Lower slowly; hits brachialis and brachioradialis']),
  ex('preacher-curl', 'Preacher Curl', ['biceps'], ['barbell'], 'intermediate',
    ['Sit at preacher bench, upper arms on pad', 'Curl barbell or dumbbell to shoulder height', 'Lower all the way down, no momentum']),
  ex('cable-bicep-curl', 'Cable Bicep Curl', ['biceps'], ['cables'], 'beginner',
    ['Stand at low cable, grip bar underhand', 'Curl to shoulder height, elbows fixed', 'Lower under constant tension']),
  ex('concentration-curl', 'Concentration Curl', ['biceps'], ['dumbbells'], 'beginner',
    ['Sit, elbow braced on inner thigh', 'Curl dumbbell up to shoulder, full peak contraction', 'Lower completely']),
  ex('reverse-curl', 'Reverse Curl', ['biceps','forearms'], ['barbell'], 'beginner',
    ['Hold barbell overhand at hip level', 'Curl to shoulder height, elbows stay fixed', 'Lower slowly; emphasizes brachialis and forearms']),
  ex('spider-curl', 'Spider Curl', ['biceps'], ['dumbbells'], 'intermediate',
    ['Lie face-down on incline bench, arms hanging', 'Curl dumbbells toward face', 'Keep upper arms vertical throughout']),

  // ── TRICEPS ────────────────────────────────────────────────────────
  ex('cable-tricep-pushdown', 'Cable Tricep Pushdown', ['triceps'], ['cables'], 'beginner',
    ['Stand at cable, bar or rope at chest height', 'Grip attachment, elbows tucked at sides', 'Push down until arms fully extended', 'Return slowly']),
  ex('skull-crusher', 'Skull Crusher', ['triceps'], ['barbell'], 'intermediate',
    ['Lie on bench, barbell or EZ-bar above chest', 'Lower bar toward forehead by bending elbows', 'Extend arms back to top, keeping upper arms vertical']),
  ex('overhead-tricep-extension', 'Overhead Tricep Extension', ['triceps'], ['dumbbells'], 'beginner',
    ['Hold one dumbbell overhead with both hands', 'Lower behind head by bending elbows', 'Extend arms overhead, keeping upper arms close to head']),
  ex('cable-overhead-extension', 'Cable Overhead Tricep Extension', ['triceps'], ['cables'], 'beginner',
    ['Face away from cable, hold rope or bar overhead', 'Lower behind head bending elbows', 'Extend arms overhead fully']),
  ex('close-grip-bench-press', 'Close-Grip Bench Press', ['triceps','chest'], ['barbell'], 'intermediate',
    ['Grip bar shoulder-width or slightly narrower', 'Lower bar to chest with elbows tucked close', 'Press back to full lockout']),
  ex('weighted-dip', 'Weighted Dip', ['triceps','chest','shoulders'], ['bodyweight'], 'advanced',
    ['Attach weight to belt, grip parallel bars, arms locked', 'Lower until upper arms parallel to floor, torso upright', 'Press to full lockout']),
  ex('tricep-kickback', 'Tricep Kickback', ['triceps'], ['dumbbells'], 'beginner',
    ['Hinge at hips, upper arm parallel to floor', 'Extend forearm back until arm is straight', 'Squeeze tricep at lockout, lower slowly']),
  ex('cable-reverse-pushdown', 'Cable Reverse Pushdown', ['triceps','forearms'], ['cables'], 'beginner',
    ['Face cable, grip bar overhand at chest level', 'Push bar down to hip level, elbows stay fixed', 'Return slowly']),
  ex('dumbbell-tate-press', 'Tate Press', ['triceps'], ['dumbbells'], 'advanced',
    ['Lie on bench, dumbbells above chest, elbows flared', 'Lower dumbbells to chest by bending elbows outward', 'Press back up by extending triceps']),
  ex('ring-dip', 'Ring Dip', ['triceps','chest','shoulders'], ['bodyweight'], 'advanced',
    ['Hold gymnastic rings, arms locked', 'Lower body until upper arms are parallel', 'Press back to lockout with control on the rings']),

  // ── QUADRICEPS ─────────────────────────────────────────────────────
  ex('barbell-back-squat', 'Barbell Back Squat', ['quadriceps','glutes','hamstrings'], ['barbell'], 'intermediate',
    ['Bar at shoulder height on rack, step under it', 'Grip slightly wider than shoulders, step back', 'Feet shoulder-width, toes slightly out', 'Descend until thighs parallel, knees tracking toes', 'Drive through heels to stand']),
  ex('front-squat', 'Front Squat', ['quadriceps','core'], ['barbell'], 'advanced',
    ['Bar rests on front delts, elbows up and forward', 'Squat to parallel or below', 'Stay upright, do not let torso fold forward', 'Drive up through heels']),
  ex('goblet-squat', 'Goblet Squat', ['quadriceps','glutes','core'], ['dumbbells'], 'beginner',
    ['Hold dumbbell vertically at chest level', 'Squat down, elbows track inside knees', 'Keep chest tall throughout', 'Drive up to standing']),
  ex('hack-squat', 'Hack Squat Machine', ['quadriceps','glutes'], ['machines'], 'beginner',
    ['Load machine, shoulder pads in place, feet mid-platform', 'Release safeties and lower until thighs parallel', 'Press back to top without locking knees']),
  ex('machine-leg-press', 'Machine Leg Press', ['quadriceps','glutes'], ['machines'], 'beginner',
    ['Sit in leg press, feet shoulder-width on platform', 'Release safeties, lower until knees at 90 degrees', 'Press through heels, do not lock knees at top']),
  ex('leg-extension', 'Leg Extension', ['quadriceps'], ['machines'], 'beginner',
    ['Sit in machine, ankles behind pad', 'Extend legs to full extension, squeeze quads', 'Lower slowly']),
  ex('bulgarian-split-squat', 'Bulgarian Split Squat', ['quadriceps','glutes'], ['dumbbells'], 'intermediate',
    ['Rear foot elevated on bench, front foot forward', 'Lower rear knee toward floor', 'Front knee stays above ankle', 'Drive through front heel to stand']),
  ex('dumbbell-lunge', 'Dumbbell Lunge', ['quadriceps','glutes','hamstrings'], ['dumbbells'], 'beginner',
    ['Stand holding dumbbells at sides', 'Step forward, lower back knee toward floor', 'Front knee above ankle, chest tall', 'Push through front heel to return']),
  ex('step-up', 'Box Step-Up', ['quadriceps','glutes'], ['dumbbells'], 'beginner',
    ['Stand in front of box or bench', 'Step onto box with one foot, drive through heel', 'Bring other foot up, stand tall', 'Step down under control']),
  ex('wall-sit', 'Wall Sit', ['quadriceps'], ['bodyweight'], 'beginner',
    ['Lean against wall, slide down until thighs parallel to floor', 'Knees at 90 degrees, back flat on wall', 'Hold position for target duration']),
  ex('walking-lunge', 'Walking Lunge', ['quadriceps','glutes'], ['dumbbells'], 'beginner',
    ['Hold dumbbells, step forward into lunge', 'Back knee lowers to floor', 'Push forward and step into next lunge', 'Continue for target reps or distance']),
  ex('box-squat', 'Box Squat', ['quadriceps','glutes'], ['barbell'], 'intermediate',
    ['Set box to parallel or just below, bar on upper back', 'Squat back and sit on box briefly', 'Drive up with force, no bouncing']),
  ex('sumo-squat', 'Sumo Squat', ['quadriceps','glutes','inner-thighs'], ['dumbbells'], 'beginner',
    ['Stand wide, toes pointed out 45 degrees, dumbbell at chest', 'Squat down until thighs parallel', 'Drive through heels, squeeze glutes at top']),
  ex('leg-press-narrow-stance', 'Narrow-Stance Leg Press', ['quadriceps'], ['machines'], 'beginner',
    ['Place feet close together in center of platform', 'Lower to 90 degrees, press through toes to target quads', 'Do not lock out at top']),
  ex('sissy-squat', 'Sissy Squat', ['quadriceps'], ['bodyweight'], 'advanced',
    ['Hold something for balance, feet narrow', 'Lean back while knees go forward over toes', 'Lower until knees nearly touch floor', 'Reverse by driving knees back']),

  // ── HAMSTRINGS ─────────────────────────────────────────────────────
  ex('lying-leg-curl', 'Lying Leg Curl', ['hamstrings'], ['machines'], 'beginner',
    ['Lie face down on machine, ankles under pad', 'Curl legs toward glutes as far as possible', 'Squeeze hamstrings at top, lower slowly']),
  ex('seated-leg-curl', 'Seated Leg Curl', ['hamstrings'], ['machines'], 'beginner',
    ['Sit in machine, thigh pad over quads, ankles on pad', 'Curl legs down and back', 'Squeeze at bottom, return slowly']),
  ex('nordic-curl', 'Nordic Hamstring Curl', ['hamstrings'], ['bodyweight'], 'advanced',
    ['Knees on pad, feet secured', 'Lower torso toward floor under control by extending knees', 'Catch yourself if needed, pull back up with hamstrings']),
  ex('stiff-leg-deadlift', 'Stiff-Leg Deadlift', ['hamstrings','glutes','back'], ['barbell'], 'intermediate',
    ['Hold barbell, minimal knee bend throughout', 'Hinge forward until strong hamstring stretch', 'Drive hips forward to return']),
  ex('single-leg-deadlift', 'Single-Leg Romanian Deadlift', ['hamstrings','glutes','core'], ['dumbbells'], 'intermediate',
    ['Stand on one leg, dumbbell in opposite hand', 'Hinge at hip, free leg extends back for balance', 'Lower dumbbell toward floor, feel hamstring stretch', 'Return to standing, squeeze glute at top']),
  ex('glute-ham-raise', 'Glute-Ham Raise', ['hamstrings','glutes'], ['machines'], 'advanced',
    ['Kneel in GHR machine, thighs on pad', 'Lower body forward, control descent with hamstrings', 'Curl body back up using hamstrings and glutes']),
  ex('swiss-ball-leg-curl', 'Swiss Ball Leg Curl', ['hamstrings','glutes'], ['bodyweight'], 'intermediate',
    ['Lie on back, heels on Swiss ball', 'Raise hips off floor, curl ball toward glutes', 'Lower under control']),
  ex('cable-leg-curl', 'Cable Leg Curl', ['hamstrings'], ['cables'], 'beginner',
    ['Attach ankle strap to low cable, face machine', 'Curl lower leg back toward glute', 'Lower slowly']),
  ex('deadlift-rdl-dumbbell', 'Dumbbell Romanian Deadlift', ['hamstrings','glutes'], ['dumbbells'], 'beginner',
    ['Stand with dumbbells at hips', 'Hinge at hips keeping dumbbells close to legs', 'Lower until hamstring stretch, return by driving hips forward']),
  ex('hip-thrust-hamstring', 'Single-Leg Hip Thrust', ['hamstrings','glutes'], ['bodyweight'], 'intermediate',
    ['Shoulders on bench, one foot on floor, other leg raised', 'Drive single foot into floor raising hips', 'Squeeze at top, lower slowly']),

  // ── GLUTES ─────────────────────────────────────────────────────────
  ex('barbell-hip-thrust', 'Barbell Hip Thrust', ['glutes','hamstrings'], ['barbell'], 'intermediate',
    ['Upper back on bench, barbell across hips', 'Drive hips up to full extension', 'Squeeze glutes hard at top for 1-2 seconds', 'Lower under control']),
  ex('glute-bridge', 'Glute Bridge', ['glutes','hamstrings'], ['bodyweight'], 'beginner',
    ['Lie on back, feet flat and close to glutes', 'Drive hips up by squeezing glutes', 'Hold 1 second at top, lower slowly']),
  ex('cable-glute-kickback', 'Cable Glute Kickback', ['glutes'], ['cables'], 'beginner',
    ['Attach ankle strap to low cable, face machine', 'Kick leg straight back, squeezing glute at peak', 'Return with control, do not swing']),
  ex('donkey-kick', 'Donkey Kick', ['glutes'], ['bodyweight'], 'beginner',
    ['On all fours, kick one leg up and back', 'Foot flexed, squeeze glute at the top', 'Lower and repeat']),
  ex('lateral-band-walk', 'Lateral Band Walk', ['glutes'], ['resistance_bands'], 'beginner',
    ['Place band around ankles or above knees', 'Step laterally with slight squat stance', 'Keep tension in band throughout']),
  ex('single-leg-glute-bridge', 'Single-Leg Glute Bridge', ['glutes','hamstrings'], ['bodyweight'], 'intermediate',
    ['Lie on back, one leg extended, other foot on floor', 'Drive through the planted foot to raise hips', 'Squeeze glute at top, lower slowly']),
  ex('dumbbell-hip-thrust', 'Dumbbell Hip Thrust', ['glutes'], ['dumbbells'], 'beginner',
    ['Upper back on bench, dumbbell across hips', 'Drive hips up to full extension', 'Squeeze glutes at top, lower slowly']),
  ex('resistance-band-glute-kickback', 'Resistance Band Glute Kickback', ['glutes'], ['resistance_bands'], 'beginner',
    ['Attach band around ankles, face wall for support', 'Kick one leg straight back, glute squeeze at peak', 'Return with control']),
  ex('frog-pump', 'Frog Pump', ['glutes'], ['bodyweight'], 'beginner',
    ['Lie on back, soles of feet together, knees out wide', 'Drive hips up squeezing glutes', 'High rep, short rest exercise']),
  ex('curtsy-lunge', 'Curtsy Lunge', ['glutes','quadriceps'], ['dumbbells'], 'intermediate',
    ['Step one foot behind and across the other', 'Lower back knee toward floor', 'Return to standing, repeat on other side']),

  // ── CORE ───────────────────────────────────────────────────────────
  ex('plank', 'Plank', ['core'], ['bodyweight'], 'beginner',
    ['Forearms on floor, body straight from head to heels', 'Engage core, glutes, and quads', 'Do not let hips sag or rise', 'Hold for target duration']),
  ex('side-plank', 'Side Plank', ['core'], ['bodyweight'], 'beginner',
    ['Lie on side, forearm on floor, feet stacked', 'Raise hips to form a straight line', 'Hold, keeping core braced', 'Repeat on other side']),
  ex('hollow-body-hold', 'Hollow Body Hold', ['core'], ['bodyweight'], 'intermediate',
    ['Lie on back, arms overhead, lower back pressed to floor', 'Raise shoulders and legs off floor simultaneously', 'Hold the hollow position, lower back stays down']),
  ex('crunch', 'Crunch', ['core'], ['bodyweight'], 'beginner',
    ['Lie on back, knees bent, hands behind head', 'Curl shoulders up squeezing abs', 'Lower under control, do not pull neck']),
  ex('bicycle-crunch', 'Bicycle Crunch', ['core'], ['bodyweight'], 'beginner',
    ['Lie on back, hands behind head, legs raised', 'Bring elbow to opposite knee while extending other leg', 'Alternate sides in a cycling motion']),
  ex('hanging-leg-raise', 'Hanging Leg Raise', ['core'], ['bodyweight','pull_up_bar'], 'intermediate',
    ['Hang from bar, legs straight down', 'Raise legs to parallel or higher while controlling swing', 'Lower slowly']),
  ex('cable-crunch', 'Cable Crunch', ['core'], ['cables'], 'beginner',
    ['Kneel at cable with rope overhead', 'Crunch elbows toward knees against resistance', 'Squeeze abs at bottom, return slowly']),
  ex('russian-twist', 'Russian Twist', ['core'], ['dumbbells'], 'beginner',
    ['Sit with knees bent, lean back slightly', 'Hold dumbbell or plate at chest', 'Rotate torso side to side touching weight to floor each rep']),
  ex('ab-wheel-rollout', 'Ab Wheel Rollout', ['core'], ['bodyweight'], 'advanced',
    ['Kneel behind ab wheel', 'Roll out as far as possible, keeping hips low', 'Contract abs to pull wheel back']),
  ex('dragon-flag', 'Dragon Flag', ['core'], ['bodyweight'], 'advanced',
    ['Lie on bench gripping edge behind head', 'Raise entire body supported only on shoulder blades', 'Lower slowly as a straight unit']),
  ex('dead-bug', 'Dead Bug', ['core'], ['bodyweight'], 'beginner',
    ['Lie on back, arms up, knees bent at 90 degrees', 'Lower opposite arm and leg toward floor', 'Lower back stays pressed to floor', 'Return and alternate']),
  ex('pallof-press', 'Pallof Press', ['core'], ['cables'], 'beginner',
    ['Stand perpendicular to cable at chest height', 'Hold handle at chest, press straight out', 'Resist rotation, hold extended, return', 'Core anti-rotation exercise']),
  ex('v-up', 'V-Up', ['core'], ['bodyweight'], 'intermediate',
    ['Lie flat, arms overhead and legs straight', 'Raise both arms and legs simultaneously, reaching for toes', 'Lower slowly, keep tension in abs']),
  ex('decline-crunch', 'Decline Crunch', ['core'], ['machines'], 'beginner',
    ['Lie on decline bench, feet secured', 'Curl shoulders up, squeezing abs', 'Lower fully, no momentum']),
  ex('landmine-rotation', 'Landmine Rotation', ['core','shoulders'], ['barbell'], 'intermediate',
    ['Stand over landmine, hold bar with both hands', 'Swing bar from one side to the other in arc', 'Resist with obliques, control the movement']),

  // ── CALVES ─────────────────────────────────────────────────────────
  ex('standing-calf-raise', 'Standing Calf Raise', ['calves'], ['bodyweight'], 'beginner',
    ['Stand on edge of step, heels off edge', 'Rise onto balls of feet as high as possible', 'Lower heels below step level for full stretch']),
  ex('seated-calf-raise', 'Seated Calf Raise', ['calves'], ['machines'], 'beginner',
    ['Sit with pad over knees, feet on platform', 'Rise up on toes as high as possible', 'Lower for full stretch']),
  ex('single-leg-calf-raise', 'Single-Leg Calf Raise', ['calves'], ['bodyweight'], 'intermediate',
    ['Stand on one foot on edge of step', 'Rise fully on ball of foot', 'Lower slowly for maximum stretch']),
  ex('leg-press-calf-raise', 'Leg Press Calf Raise', ['calves'], ['machines'], 'beginner',
    ['Sit in leg press, feet at bottom edge of platform', 'Extend ankles to push platform with balls of feet', 'Lower heels back for stretch']),
  ex('donkey-calf-raise', 'Donkey Calf Raise', ['calves'], ['machines'], 'intermediate',
    ['Lean forward on pad, feet on calf raise platform', 'Rise on balls of feet, full range of motion', 'Lower fully each rep']),

  // ── KETTLEBELL ─────────────────────────────────────────────────────
  ex('kettlebell-swing', 'Kettlebell Swing', ['glutes','hamstrings','core'], ['kettlebell'], 'intermediate',
    ['Stand shoulder-width, bell on floor in front', 'Hike bell back between legs', 'Drive hips forward explosively to swing to chest', 'Let it swing back and repeat, power from hips not arms']),
  ex('kettlebell-goblet-squat', 'Kettlebell Goblet Squat', ['quadriceps','glutes','core'], ['kettlebell'], 'beginner',
    ['Hold kettlebell by horns at chest', 'Squat deep, elbows inside knees', 'Drive up through heels, stay tall']),
  ex('kettlebell-clean', 'Kettlebell Clean', ['glutes','core','shoulders'], ['kettlebell'], 'intermediate',
    ['Start in a swing, redirect bell path into a rack position', 'Bell wraps around arm into front rack at shoulder', 'Hinge back down to swing position']),
  ex('kettlebell-snatch', 'Kettlebell Snatch', ['glutes','shoulders','core'], ['kettlebell'], 'advanced',
    ['Swing bell to hip level, punch fist through and overhead', 'Bell lands softly overhead in a locked position', 'Lower in a controlled arc back to swing']),
  ex('turkish-get-up', 'Turkish Get-Up', ['core','shoulders','glutes'], ['kettlebell'], 'advanced',
    ['Lie with bell pressed overhead, arm vertical', 'Roll to elbow, then hand, then sweep leg through', 'Stand up while keeping bell locked overhead', 'Reverse the sequence to lie back down']),
  ex('kettlebell-press', 'Kettlebell Press', ['shoulders','triceps'], ['kettlebell'], 'intermediate',
    ['Hold bell in rack position at shoulder', 'Press straight up to full lockout', 'Lower back to rack under control']),
  ex('kettlebell-row', 'Kettlebell Row', ['back','biceps'], ['kettlebell'], 'beginner',
    ['Place one hand on bench, hold bell in other', 'Row bell to hip, elbow driving back', 'Squeeze lat at top, lower slowly']),
  ex('kettlebell-deadlift', 'Kettlebell Deadlift', ['glutes','hamstrings','back'], ['kettlebell'], 'beginner',
    ['Bell between feet, hinge to grip it', 'Stand up by driving hips forward', 'Lower with hinge, control descent']),
  ex('kettlebell-windmill', 'Kettlebell Windmill', ['core','shoulders','hamstrings'], ['kettlebell'], 'advanced',
    ['Press bell overhead, lock arm', 'Hinge to side reaching free hand toward floor', 'Keep eyes on the bell throughout', 'Return upright']),
  ex('kettlebell-lunge', 'Kettlebell Lunge', ['quadriceps','glutes'], ['kettlebell'], 'beginner',
    ['Hold kettlebells at sides or in rack position', 'Step forward, lower back knee', 'Drive through front heel to return']),

  // ── RESISTANCE BAND ────────────────────────────────────────────────
  ex('resistance-band-squat', 'Resistance Band Squat', ['quadriceps','glutes'], ['resistance_bands'], 'beginner',
    ['Stand on band, hold handles at shoulder level', 'Squat to parallel, band provides resistance on the way up', 'Return to standing']),
  ex('resistance-band-deadlift', 'Resistance Band Deadlift', ['hamstrings','glutes','back'], ['resistance_bands'], 'beginner',
    ['Stand on band, hold ends at hips', 'Hinge at hips, lower hands toward floor', 'Drive hips forward, stand tall']),
  ex('resistance-band-row', 'Resistance Band Seated Row', ['back','biceps'], ['resistance_bands'], 'beginner',
    ['Sit with feet on band, hold ends', 'Row handles to sides of torso, squeezing shoulder blades', 'Return to full arm extension']),
  ex('resistance-band-chest-press', 'Resistance Band Chest Press', ['chest','triceps'], ['resistance_bands'], 'beginner',
    ['Anchor band behind you at chest height', 'Press handles forward to full extension', 'Return under control']),
  ex('resistance-band-bicep-curl', 'Resistance Band Bicep Curl', ['biceps'], ['resistance_bands'], 'beginner',
    ['Stand on band, hold ends palms up', 'Curl handles to shoulders', 'Lower slowly']),
  ex('resistance-band-tricep-extension', 'Resistance Band Tricep Extension', ['triceps'], ['resistance_bands'], 'beginner',
    ['Anchor band overhead, face away', 'Hold overhead, elbows bent', 'Extend arms forward and down to full extension']),
  ex('resistance-band-lateral-raise', 'Resistance Band Lateral Raise', ['shoulders'], ['resistance_bands'], 'beginner',
    ['Stand on band, hold ends at sides', 'Raise arms out to shoulder height', 'Lower slowly']),
  ex('resistance-band-pull-apart', 'Resistance Band Pull-Apart', ['shoulders','back'], ['resistance_bands'], 'beginner',
    ['Hold band at shoulder width in front', 'Pull band apart to full extension across chest', 'Return slowly, keep arms straight']),
  ex('resistance-band-glute-bridge', 'Resistance Band Glute Bridge', ['glutes'], ['resistance_bands'], 'beginner',
    ['Lie on back, band across hips anchored by hands', 'Drive hips up against resistance', 'Squeeze at top, lower slowly']),
  ex('resistance-band-monster-walk', 'Resistance Band Monster Walk', ['glutes'], ['resistance_bands'], 'beginner',
    ['Band around ankles or above knees', 'Walk in a wide stance forward, backward, or side to side', 'Maintain tension throughout']),

  // ── FULL BODY / CARDIO ─────────────────────────────────────────────
  ex('burpee', 'Burpee', ['core','chest','quadriceps'], ['bodyweight'], 'intermediate',
    ['Stand, drop hands to floor, jump feet back to push-up position', 'Perform one push-up', 'Jump feet forward, explode up with a jump and clap overhead']),
  ex('mountain-climber', 'Mountain Climber', ['core','chest','cardio'], ['bodyweight'], 'beginner',
    ['Start in high push-up position', 'Drive one knee toward chest, then quickly switch legs', 'Keep hips level, move as fast as controlled']),
  ex('jump-squat', 'Jump Squat', ['quadriceps','glutes','calves'], ['bodyweight'], 'intermediate',
    ['Squat to parallel', 'Explode up, leaving the ground', 'Land softly with bent knees, absorb impact', 'Immediately descend into next rep']),
  ex('thruster', 'Thruster', ['quadriceps','shoulders','core'], ['barbell'], 'advanced',
    ['Hold barbell in front rack, squat to parallel', 'Drive up explosively, use momentum to press bar overhead', 'Lower bar to rack and repeat']),
  ex('box-jump', 'Box Jump', ['quadriceps','glutes','calves'], ['bodyweight'], 'intermediate',
    ['Stand in front of box', 'Swing arms and hinge hips, jump onto box', 'Land softly with bent knees', 'Step back down']),
  ex('jumping-jack', 'Jumping Jack', ['cardio'], ['bodyweight'], 'beginner',
    ['Stand with feet together, arms at sides', 'Jump feet wide while raising arms overhead', 'Jump back to start position', 'Repeat at consistent tempo']),
  ex('high-knee-run', 'High Knees', ['cardio','core'], ['bodyweight'], 'beginner',
    ['Run in place, driving knees as high as possible', 'Pump arms in opposition to legs', 'Maintain fast pace']),
  ex('battle-rope-wave', 'Battle Rope Wave', ['shoulders','core','cardio'], ['machines'], 'beginner',
    ['Hold rope ends, stand in athletic stance', 'Alternately raise and lower each arm creating waves', 'Drive waves all the way to anchor']),
  ex('sled-push', 'Sled Push', ['quadriceps','glutes','cardio'], ['machines'], 'intermediate',
    ['Grip sled handles or posts low', 'Drive forward with powerful leg strides', 'Keep torso at a forward lean']),
  ex('jump-rope', 'Jump Rope', ['calves','cardio'], ['bodyweight'], 'beginner',
    ['Hold rope handles, feet together', 'Swing rope and jump over it with small hops', 'Stay on balls of feet, keep elbows at sides']),
  ex('clean-and-press', 'Dumbbell Clean and Press', ['glutes','shoulders','core'], ['dumbbells'], 'intermediate',
    ['Dumbbells at floor, hip hinge', 'Explosively clean dumbbells to shoulders', 'Press overhead to full lockout', 'Lower and return to floor']),
  ex('devil-press', 'Devil Press', ['chest','shoulders','glutes','core'], ['dumbbells'], 'advanced',
    ['Perform a burpee with dumbbells on floor', 'On the way up, clean-and-press both dumbbells overhead', 'Lower and repeat']),
  ex('farmer-walk', 'Farmer Walk', ['traps','core','grip'], ['dumbbells'], 'beginner',
    ['Hold heavy dumbbells or kettlebells at sides', 'Walk a set distance with upright posture', 'Keep core tight and shoulders level']),
  ex('renegade-row', 'Renegade Row', ['back','core','chest'], ['dumbbells'], 'advanced',
    ['Start in push-up position with dumbbells on floor', 'Row one dumbbell to hip while balancing on other', 'Keep hips square, alternate sides']),
  ex('thruster-dumbbell', 'Dumbbell Thruster', ['quadriceps','shoulders'], ['dumbbells'], 'intermediate',
    ['Hold dumbbells at shoulder height', 'Squat to parallel, drive up explosively', 'Use momentum to press dumbbells overhead', 'Lower to shoulders and repeat']),

  // ── ADDITIONAL BODYWEIGHT ──────────────────────────────────────────
  ex('pike-push-up', 'Pike Push-Up', ['shoulders','triceps'], ['bodyweight'], 'intermediate',
    ['Start in downward dog position with hips high', 'Lower head toward floor by bending elbows', 'Push back to start']),
  ex('archer-push-up', 'Archer Push-Up', ['chest','triceps'], ['bodyweight'], 'advanced',
    ['Start in wide push-up position', 'Lower to one side, extending opposite arm straight', 'Push back up, alternate sides']),
  ex('pistol-squat', 'Pistol Squat', ['quadriceps','glutes','core'], ['bodyweight'], 'advanced',
    ['Stand on one leg, other leg extended forward', 'Lower on one leg to full depth', 'Drive back up, keep extended leg off floor throughout']),
  ex('jump-lunge', 'Jump Lunge', ['quadriceps','glutes'], ['bodyweight'], 'intermediate',
    ['Start in lunge position', 'Jump explosively, switching leg positions in midair', 'Land in opposite lunge, absorb impact']),
  ex('broad-jump', 'Broad Jump', ['quadriceps','glutes','calves'], ['bodyweight'], 'intermediate',
    ['Stand with feet hip-width', 'Swing arms and hinge hips, jump forward as far as possible', 'Land with bent knees, stick the landing']),
  ex('lateral-squat', 'Lateral Squat', ['quadriceps','glutes','inner-thighs'], ['bodyweight'], 'beginner',
    ['Stand wide, shift weight to one side', 'Squat down on one leg, other leg straight', 'Drive back to center, repeat other side']),
  ex('cossack-squat', 'Cossack Squat', ['quadriceps','glutes','inner-thighs'], ['bodyweight'], 'intermediate',
    ['Stand wide, toes slightly out', 'Squat deep to one side, opposite leg fully extended', 'Sit into the hip, return to center, alternate sides']),
  ex('tuck-jump', 'Tuck Jump', ['quadriceps','calves','core'], ['bodyweight'], 'intermediate',
    ['Stand with slight squat', 'Jump and pull both knees toward chest', 'Land softly, immediately jump again']),
  ex('bear-crawl', 'Bear Crawl', ['core','shoulders','quadriceps'], ['bodyweight'], 'beginner',
    ['On all fours with knees hovering just off ground', 'Crawl forward moving opposite hand and foot', 'Keep back flat, hips low']),
  ex('inchworm', 'Inchworm', ['core','hamstrings','chest'], ['bodyweight'], 'beginner',
    ['Stand, hinge forward and walk hands out to push-up position', 'Perform a push-up, then walk feet toward hands', 'Stand and repeat']),
];

async function main() {
  console.log(`Seeding ${EXERCISES.length} exercises...`);
  const { error } = await supabase
    .from('exercises')
    .upsert(EXERCISES, { onConflict: 'slug' });
  if (error) {
    console.error('Seed failed:', error.message);
    process.exit(1);
  }
  console.log(`Seeded ${EXERCISES.length} exercises successfully.`);
}

main();
